######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 27 16:44:56 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += widget

# Input
HEADERS += MainWindow.h Plotting.h
SOURCES += main.cpp MainWindow.cpp Plotting.cpp
RESOURCES += spreadsheet.qrc
